feat/token
verdaccio/local-storage pull request #168
Opened 2019-06-11 07:00 UTC by juangabreil

**Type:** feature

The following has been addressed in the PR:

- There is a related issue? verdaccio/verdaccio#541
 - Unit or Functional tests are included in the PR yes

**Description:** This PR adds support to save, delete and read tokens in a leveldb.

2019-06-12 13:46 UTC, juanpicado commented
hi @juangabreil before you continue, I think you need to read a previous conversation about using Level https://github.com/verdaccio/local-storage/pull/165#issuecomment-491956157

2019-06-12 13:55 UTC, juanpicado reviewed
Overall looks good (I haven't run any test yet), but unfortunately we cannot use `leveldb`, the reason is we cannot have any external dependency, so token.json should be a separated plain file.

2019-06-12 14:01 UTC, juangabreil commented
I don't fully understand the issue. Level stores db in a couple of files but I can switch to plain json files

2019-06-12 14:03 UTC, juangabreil commented
I mean, I didn't have to compile anything. Just install level and work with it

2019-06-12 17:32 UTC, juanpicado commented
Ok, Then we had some sort of misunderstanding, let me check your PR and run some test before you remove something. I will dig in to leveldb

2019-06-12 17:33 UTC, juanpicado commented
Ahh, ok install level, that is the point, we have 0 dependencies, so, install level is one step we cannot afford, we need to switch this PR to plain files.

2019-06-12 17:56 UTC, juangabreil commented
Sorry, crazy day. With install I meant npm install --save level (yarn add level) and start working. Nothing else to do

2019-06-14 11:49 UTC, juangabreil commented
So are we trying this approach or are we using the plain json one?

2019-06-14 12:09 UTC, juanpicado commented
@juangabreil let me some days 🙏  to test this, I'll back to you whether I find something o we have to do any further change.

2019-06-26 14:13 UTC, juanpicado commented
Some thoughts about Level, there are no external dependencies, so cool. Here a video about it https://www.youtube.com/watch?v=sR7p_JbEip0

I still have to test this locally, but, seems promising.

2019-07-09 07:10 UTC, NathanaelA commented
@juanpicado - I was under the impression the reason you didn't want to use LevelDB was because you didn't want the additional dependencies.   If you are considering LevelDB, you might want to consider SQLite; because it is multithreaded and allows  multiple node process's to access the DB where my understanding of LevelDB is it is single process only...    If we want to scale this up; LevelDB is going to be a problem...

2019-07-18 13:29 UTC, juanpicado commented
@NathanaelA thanks for your feedback, but, this plugin a this stage is not support multi process anyway, this PR is just for tokens which I asume will handle a really low number of request. For this purpose I think https://github.com/Level/level-js makes the work, I considered https://www.npmjs.com/package/sqlite3 before which is cool but I'd rather use it as a global database, perhaps a plugin named `verdaccio-storage-sqlite3`? It would be a nice PoC and perhaps the future of the core db if this project.

2019-07-18 13:31 UTC, juanpicado commented
@juangabreil could to resolve those conflicts?

2019-07-18 15:39 UTC, juangabreil commented
Done :)

2019-07-18 17:29 UTC, NathanaelA commented
@juanpicado - I do realize what your purpose for using LevelDB is.  :)     I've been following the token threads for a while; I had to come up with a different method to solve parts of this issue as I needed ability to dynamically add people to the access list but not give them rights to create the users themselves.  

I'm just trying to say if you are making a choice to force a DB engine for this specific purpose; you might as well choose properly up front and use a technology that does allow multiple access for later.  :)      Its all about choosing the foundation for v5,v6,v7 right now, even if you aren't using some of those specific features until possibly much later...  :grinning:        At this point Sqlite vs LevelDB adds about the same amount of requirements to the project, but only one of them is multi-process compatible.

Once you have a real db added to the project; several things will probably migrate to using it over the next couple versions, I know in my case I have several features (download counts & other statistics) that I need that would rely on having a decent db backend.    

So either you have to plan to have a really simple database interface (ie. `const record = getkey({"id":"1234"});` )  so that the db engine can be easily swapped out, or you need to choose to use a specific database right now that you believe is the best choice for the project for the long term...

2019-08-03 07:25 UTC, juanpicado commented
Thanks @NathanaelA for your insights, I completely understand the concerns exposed. Scale verdaccio was one of the big task I took years ago https://github.com/verdaccio/verdaccio/issues/103 and due such request we introduced the Storage API (it is no perfect, but fulfill many requirements). As I exposed  in other threads, if any one needs to scale, just use a different plugin. 

This default storage plugin (before was built-in) was designed (by his author) for a single process  and I do not intend to change that. For this task,  `leveldb` does the job, token is not an intensive task and works fine. 

I prefer flexible project with interchangeable parts creating a variate ecosystem that something built-in  fulfill all requirements, that would be unmanageable with our limite resources, so the heavy part is distributed by several plugin authors. This model works fine, since many use for instance, GitLab auth plugins, and I do not have to deal with that. 

So, I'm not disagree with you, just I think we see the same problem from different perspectives. 👍

2019-08-03 07:29 UTC, juanpicado requested changes
Hi @juangabreil 

sorry my delay, I've been testing your changes, works pretty good. But we must change couple of things.

on `readTokens` you need to return the value rather the whole field, this is because I expect a `Token[]` list object in the other side, that's what we need to deliver here.

```
 stream.on('data', data => {
        tokens.push(data.value);
      });
```
Please, try to use curly brakets, it makes my life easier when I debug.

The second thing we must change, is the database folder name, 

```
const TOKEN_DB_NAME = '.token-db';
```

The reason here, is the database lives in the same folder of the packages, so, it can be easily removed if is not hidden.

I'm still testin git, I must test remove packages, but works really nice. I'm finishing the endpoints (continuing the job started by @Eomm )

Something additional is missing, is update the readme, we must document about the new database, so people is aware of it. 

I'd recommend describe it in the README, what kind of database, some suggestions about how they can inspect it and the shape of the object we are storing into it. Where is located? 
That would be great so will solve many doubts in the future.

2019-08-03 07:35 UTC, juanpicado commented
Some FYI notes, once we finish this, we are moving this plugin into https://github.com/verdaccio/monorepo project. This is the latest PR I'm accepting in this repo, so I can move it completely there.

2019-08-03 07:43 UTC, juanpicado commented
Sorry for the conflicts @juangabreil, there was another PR merged.

2019-08-04 11:17 UTC, juangabreil commented
Ok, I will do those changes. But do you want me to do them in this branch or the one you are using for testing?

2019-08-04 11:18 UTC, juanpicado commented
> Ok, I will do those changes. But do you want me to do them in this branch or the one you are using for testing?

In yours, but I tell u in advance I had to solve many conflicts in test, just use mine as a guide.

2019-08-08 17:27 UTC, juanpicado commented
Thanks @juangabreil I'll test on my end and I'll back to you soon. The plan is ship this at the end of the month.

2019-08-12 05:57 UTC, juangabreil commented
If you need help with more things, just let me know :)

2019-08-12 06:13 UTC, juanpicado commented
Hi, I will do it soon, thanks for the reminder. :)

2019-08-12 19:22 UTC, juanpicado approved these changes
Thanks so much @juangabreil  !! I'll try to move this forward for the next minor release.

2019-08-13 04:58 UTC, merged

2019-08-13 06:05 UTC, juangabreil commented
What else I can do for contributing in this feature?

2019-08-13 06:21 UTC, juanpicado commented
The current state is defined in the main ticket (check references above), actually I am testing it but I found an design issue, the current default token signature always  return the same token for the same combination (user + password) while using JWT does not happen. So the npm token list will retrieve always one token for this user. I am not sure yet how to address this since I cannot do anything without break the major version.

For the other side, all endpoints are ready, but need testing and see all features works fine. Unit testing and functional testing are required before ship it, that will take a while. You might contribute with me there hand to hand if you will. 

Something else is we can revoke only by ID since we do not save the token (check the npm token revoke docs) and it is not a limitation but let see what we can do there.

So, my priority now is first do some manual testing and see whether the current implementation fill all major gaps and is good enough for the public. 

Btw, one thing is not implemented yet in the main project is ... once the token is saved, Verdaccio does not check against this database whether the token is there (for JWT) is unnecessarily since we rely on the signature but for the legacy token signature I am not sure about it yet.

2019-08-13 06:24 UTC, juanpicado commented
https://github.com/verdaccio/verdaccio/pull/1427